### ISSUE TITLE
Can't send command to bill acceptor

### ISSUE THREAD

**Issue by scorpioRED** [direktspeed/ds-cctalk#11]
Hi!
I try to run exemple.js, with small modifications:
`const bus = require('ds-cctalk/index')
const cctalk = new bus()

cctalk
  .on('open', ()=> {
    console.log('port opened')
    cctalk.send(new cctalk.CCCommand(1 ,2, 245)).then((cmdResp) =>{
        console.log('resp => ', cmdResp)
    }).catch((respErr) =>{
      console.log('resp err => ', respErr)
    })

  })
  .on('data', (command) => {
    console.log('on data -> ', command)
    // Identify Coins emit accepted

  })
  .on('close', () => {
    console.log('cctalk::onClose');
  })
  .on('error', (err) => console.log('error',err));`  

But I got an error :

> NEW CCBus CONFIG In: undefined  -> CONFIG Out:  { timeout: 2000, src: 1 }
> port opened
> resp err =>  { Error
>     at new module.exports.TimeoutError (/home/user/tst/dsc/node_modules/promise-timeout/index.js:44:16)
>     at module.exports.timeout (/home/user/tst/dsc/node_modules/promise-timeout/index.js:20:15)
>     at CCBus.send (/home/user/tst/dsc/node_modules/ds-cctalk/index.js:110:19)
>     at CCBus.cctalk.on (/home/user/tst/dsc/node_modules/ds-cctalk/examples.js:7:12)
>     at emitNone (events.js:106:13)
>     at CCBus.emit (events.js:208:7)
>     at SerialPort.bus.SerialPort.on (/home/user/tst/dsc/node_modules/ds-cctalk/index.js:66:14)
>     at emitNone (events.js:106:13)
>     at SerialPort.emit (events.js:208:7)
>     at SerialPort.<anonymous> (/home/user/tst/dsc/node_modules/serialport/lib/serialport.js:188:10)
>   stack: 'Error\n    at new module.exports.TimeoutError (/home/user/tst/dsc/node_modules/promise-timeout/index.js:44:16)\n    at module.exports.timeout (/home/user/tst/dsc/node_modules/promise-timeout/index.js:20:15)\n    at CCBus.send (/home/user/tst/dsc/node_modules/ds-cctalk/index.js:110:19)\n    at CCBus.cctalk.on (/home/user/tst/dsc/node_modules/ds-cctalk/examples.js:7:12)\n    at emitNone (events.js:106:13)\n    at CCBus.emit (events.js:208:7)\n    at SerialPort.bus.SerialPort.on (/home/user/tst/dsc/node_modules/ds-cctalk/index.js:66:14)\n    at emitNone (events.js:106:13)\n    at SerialPort.emit (events.js:208:7)\n    at SerialPort.<anonymous> (/home/user/tst/dsc/node_modules/serialport/lib/serialport.js:188:10)',
>   message: 'Timeout' }

What's wrong?

**Comment by frank-dspeed** [comment]
without knowing your code i can't tell you that i only know my code workes in production but you don't need this module to use cctalk for sending and reciving its only a framework 

i implamented a nativ cctalk parser for serialport maybe you want to use that directly

**Comment by scorpioRED** [comment]
Above is a full code. Actually, it's your code from the example.js
And when I try to use code from README:

```
const cc = require('ds-cctalk')

// Use
cc.device() // Register / Create a Device
cc.bus() // Open a new Connection gets used by device if not defined befor
cc.command() // gets used by bus and device for the sendCommand and sendCommandRaw prototypes
// running this file as main
if(!module.parent) {

  var usbBus =  new CCBus('/dev/ttyUSB0');

  var cd = new require(usbBus, { dest: 2, timeout: 1000 });

  cd.on('error', function(e) {
    debug('emp800::')(e);
  });

  cd.on('ready', function() {
    try {
      debug('emp800::')('ready');
      cd.enableAcceptance();
      cd.setAcceptanceMask(0xFFFF);
      // Example sendCommand for usage see CCTalk Spec for more information
      // cd.sendCommand({ src: 1, dest: 2, command: 231, data: new Uint8Array(0) });
      cd.on('error', function(e) { debug('emp800::')('error', e); });
      cd.on('accepted', function(c) {
        debug('emp800::')('Accepted', c);
        cd.getCoinName(c).then(function(name) { debug('emp800::')(name); });
      });
      cd.on('inhibited', function(c) {
        debug('emp800::')('Inhibited', c);
        cd.getCoinName(c).then(function(name) { debug('emp800::')(name); });
      });
      cd.on('rejected', function(c) { debug('emp800::')('Rejected', c); });
    } catch(e) {
      debug('emp800::')(e, e.stack);
    }
  });


}
```

 I also got an error that _cc.device is not a function_

**Comment by scorpioRED** [comment]
If I try to use just cctalk parser for node serialport, I also got an error 

```
const parser = port.pipe(new CCtalk())
                             ^

ReferenceError: CCtalk is not defined
    at Object.<anonymous> (/home/user/tst/custom/index.js:10:30)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

```

**Comment by frank-dspeed** [comment]
@scorpioRED what is your current nodejs version?

**Comment by frank-dspeed** [comment]
it looks like there is something wrong with your environment as you defined CCTalk as const and the error says there is no CCtalk defined i would suggest you correct your code
to use CCTalk and not CCtalk

**Comment by frank-dspeed** [comment]
```
const CCTalk = require('@serialport/parser-cctalk')
const parser = port.pipe(new CCtalk()) // <= here you need to put CCTalk as that is the name of your constant.
```

**Comment by scorpioRED** [comment]
I am very ashamed, it was stupid mistake :(
And could you be so kind and show me, how do I use your native cctalk parser?
Because I could not find any examples, and [docs](https://serialport.io/docs/en/api-parser-cctalk) not very informative

**Comment by frank-dspeed** [comment]
@scorpioRED i have at present no free resources for education about the cctalk protocol and usage with nodejs if you like you can write me a email to frank@dspeed.eu or msg me there via google hangouts then we could talk about ways to support you i think i can invest 1 hour via Anydesk or some other remote control to debug your code. In general you will need a understanding of the cctalk protocol implamentation of your device i am not sure which device your using.
